### ISSUE TITLE
nginx-proxy_db bind mount error

### ISSUE THREAD

**Issue by nativeit** [caprover/caprover#1226]
**IMPORTANT:** This is a bug report. If you are having problem with deploying a particular app use the deployment issue type.

> If you are having problems with deploying a particular app using a customized dockerfile - please change your questions to Dockerfile and post it where appropriate such as StackOverflow. This is a Docker question, not a CapRover specific issue.

---

**What is the problem?**
The bind mount for nginx-proxy_db calls for a local directory that doesn't typically exist: `/data/compose/4/data/mysql`

This caused the container to fail to start, and a ton of errors to flood the syslog. I'm not sure if it caused any further backend issues, my existing applications all seem to be functioning, but I would imagine it might start causing issues if SSL certs began expiring. It may/may not be an issue with new apps, but I'm currently having the same rate limit problem referenced in issue #1189, so I haven't been able to deploy any new apps since I discovered this.

If applicable, content of `captain-definition` file:

**Steps to reproduce the problem:**
Just look in `/var/log/syslog`, it's throwing errors every minute or so.

**Output of the following command on your server:**

```
uname -a && lsb_release -a && free -h

Linux docker.ntv.one 4.19.0-11-amd64 #1 SMP Debian 4.19.146-1 (2020-09-17) x86_64 GNU/Linux
No LSB modules are available.
Distributor ID: Debian
Description:    Debian GNU/Linux 10 (buster)
Release:        10
Codename:       buster
              total        used        free      shared  buff/cache   available
Mem:          3.9Gi       1.3Gi       575Mi        70Mi       2.0Gi       2.4Gi
Swap:            0B          0B          0B
Total:        3.9Gi       1.3Gi       575Mi
```

**Comment by githubsaturn** [comment]
What's "nginx-proxy_db"? There is no such a thing in CapRover.

**Comment by githubsaturn** [comment]
Regarding the docker hub limit. 
- What version of CapRover are you running?
- What's the output of this? `cat /captain/data/config-captain.json | jq ".dockerRegistries[].registryDomain"`

**Comment by nativeit** [comment]
Just on the off-chance it's relevant, this is the error I'm getting when attempting to deploy Adminer that seems to be causing it to fail and retry repeatedly, resulting in a flood of pull requests.

Oct 16 14:58:23 docker dockerd[639]: time="2021-10-16T14:58:23.940752853-04:00" level=info msg="Attempting next endpoint for pull after error: manifest unknown: Failed to fetch \"4\" from request \"/v2/library/adminer/manifests/4\"."

I will troubleshoot this myself, and see if the problem exists on a dev machine. It seems like it might be connected, but I'd just be guessing.

**Comment by githubsaturn** [comment]
> As of today, it appears I am successfully able to deploy apps again, but I imagine that's just because the unauthenticated limit has since timed out and reset. As others have experienced, a problematic image/service (in my case, I was attempting to deploy Adminer) results in Docker pulling the image over and over, very quickly hitting the 200 pull limit. I will dig into the issues I'm having with Adminer specifically later, as I have no reason to think it's related to any of the above.

There is definitely an issue that I just identified and fixed here: https://github.com/caprover/caprover/commit/a634e494eb571edb7d8a68cf06f32aceee56a144
We previously failed to attach the auth token to images that don't have a `user/repo` format. `adminer` is one example. It's fixed in the commit that I mentioned above. Previously, before this commit, the registry had to be explicitly set to `registry-1.docker.io`, but after this commit `docker.io` `registry-1.docker.io` and `hub.docker.com` all work... 

You can wait about an hour for the edge image to get pushed and update your image to `edge` to test it out. 



RE: Attempting next endpoint for pull after error

It might be fixed after this commit above, but I'll look into it further.

**Comment by nativeit** [comment]
That all makes sense, thanks again for everything you do! I'll be sure that I am on `edge` with the relevant commit later today before I test and report back.

**Comment by nativeit** [comment]
FYI, Adminer still fails deployment with default settings, but if I change the tag from "4" to "latest" it works just fine. I think this particular issue can be closed. Thanks again for all your help!

**Comment by githubsaturn** [comment]
Great! Thanks for confirming the fix!

When you say "_Adminer still fails deployment with default settings_", does this mean that you are trying to deploy a fresh / new Adminer as a one-click app and it fails to deploy?

**Comment by nativeit** [comment]
My apologies for the ambiguity, that was an attempt to deploy Adminer as a fresh one-click app specifically with leaving the default version tag of "4" (a second attempt using "latest" succeeded), although I just tried to recreate the issue by deploying Adminer with the default tag and it completed without any problems, so it was either another symptom that got resolved with a634e49, or otherwise unrelated. Either way, it's working normally with its default settings right now. 

While I have you, a quick question--how do you prefer to handle minor corrections to non-critical things like broken links, typos, and/or syntax mistakes (that otherwise don't affect functionality)? Are those kind of things worth the effort of a PR, or do you prefer to bundle them in with more significant updates?

**Comment by githubsaturn** [comment]
> While I have you, a quick question--how do you prefer to handle minor corrections to non-critical things like broken links, typos, and/or syntax mistakes (that otherwise don't affect functionality)? Are those kind of things worth the effort of a PR, or do you prefer to bundle them in with more significant updates?

Yes, definitely. Small PRs are definitely welcomed! Examples:
https://github.com/caprover/caprover-website/search?q=typo&type=issues
https://github.com/caprover/caprover-frontend/search?q=typo&type=issues
