### ISSUE TITLE
UI issue

### ISSUE THREAD

**Issue by drmrbrewer** [caprover/caprover#133]
Having logged out of the Captain web console, when I browse back to the login page later, I see a brief flash of the *logged in* page, before it is replaced by the login page.

**Comment by githubsaturn** [comment]
Fixed
https://github.com/githubsaturn/captainduckduck/commit/c8b044887a6254d32ef6a65338a2fbf2879fdb7f

Will be released in the next version

**Comment by drmrbrewer** [comment]
BTW I'm still seeing a flash of the logged in page even with Captain 0.6.0, just before the login page appears.

**Comment by githubsaturn** [comment]
I cannot see what you're seeing. Do you see the blue left navbar? Or you just see the loading state before login page appears?

**Comment by danielivert** [comment]
I have the same issue. The left sidebar dissappeared but we can see a quick "flash" of an empty Dashboard. I believe it's the div with class `page-content`

**Comment by githubsaturn** [comment]
Done in  https://github.com/caprover/caprover/releases/tag/v1.0.0
